---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset-azurefile-win
  labels:
    app: busybox
spec:
  serviceName: statefulset-azurefile-win
  podManagementPolicy: Parallel  # default is OrderedReady
  replicas: 1
  template:
    metadata:
      labels:
        app: busybox
    spec:
      nodeSelector:
        "kubernetes.io/os": windows
      containers:
        - name: statefulset-azurefile
          image: mcr.microsoft.com/windows/servercore:ltsc2022
          command:
            - "powershell.exe"
            - "-Command"
            - "while (1) { Add-Content -Encoding Ascii C:\\mnt\\azurefile\\data.txt $(Get-Date -Format u); sleep 1 }"
          volumeMounts:
            - name: persistent-storage
              mountPath: /mnt/azurefile
  updateStrategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: busybox
  volumeClaimTemplates:
    - metadata:
        name: persistent-storage
      spec:
        storageClassName: azurefile-csi
        accessModes: ["ReadWriteMany"]
        resources:
          requests:
            storage: 100Gi
